### ISSUE TITLE
說明建議

### ISSUE THREAD

**Issue by oniondelta** [Ponpon55837/Squirrel#1]
你好！

「、」可用「Shift」+「 ' 」打出呀！
「Shift」+「符號鍵位」⇨ 多為常用符號

修改候選詞的數量，除修改「 page_size: 」外，建議再修改：
alternative_select_keys: "QAZWSX" 
↓
alternative_select_keys: "QAZWSXE" 
（選字比較方便，shift+QAZWSXE 可選字直接上屏）

**Comment by Ponpon55837** [comment]
好的 感謝你的建議  已經修正內容了
