### ISSUE TITLE
感覺README可以提到切換繁體簡體？

### ISSUE THREAD

**Issue by nyngwang** [Ponpon55837/Squirrel#12]
如題，很感謝您製作這個設定懶人包（？
本來想提問怎麼切換繁體简体，結果在您提供的pdf檔案裡面得到答案。

感覺可以在README中提到（或者這其實是常識？那麼您可以直接關閉這個issue！）

**Comment by Ponpon55837** [comment]
好的  感謝你的建議 已補上說明
