### ISSUE TITLE
請問如何關閉逐鍵提示

### ISSUE THREAD

**Issue by williamyyu** [Ponpon55837/Squirrel#2]
我嘗試將 `translator/enable_completion: false` 放入 default.custom.yam 跟 squirrel.custom.yaml
不過都沒有用，請問有辦法關閉逐鍵提示嗎？
謝謝

**Comment by Ponpon55837** [comment]
請問你的逐鍵提示是怎樣的
因為在bopomo_onion.schema.yaml當中已經有寫translator/enable_completion: false了
![Snip20210108_10](https://user-images.githubusercontent.com/32410486/103970228-afbec900-51a2-11eb-916d-71879979dc2b.png)

**Comment by Ponpon55837** [comment]
請問你的逐鍵提示有圖片嗎
因為在bopomo_onion.schema.yaml裡面的translators底下的
- table_translator@bopomo_onion_phrase
- script_translator@reverse2_lookup
![Snip20210108_11](https://user-images.githubusercontent.com/32410486/103970393-22c83f80-51a3-11eb-9455-976ff255498a.png)

已經有做enable_completion: false
![Snip20210108_10](https://user-images.githubusercontent.com/32410486/103970410-2c51a780-51a3-11eb-8920-cad8a00baafc.png)

另外如果要在squirrel.custom.yaml底下的patch使用translators/enable_completion: false要記得縮排只有一個空格
patch:
 translators/enable_completion: false
