### ISSUE TITLE
MacOS verison: monterey doesn't work

### ISSUE THREAD

**Issue by a0917bc** [Ponpon55837/Squirrel#3]
目前最新版macOS無法使用，有什麼方法知道要怎麼做嗎？

**Comment by Ponpon55837** [comment]
目前就我所知 有兩種解法

1. https://github.com/LEOYoon-Tsaw/squirrel/releases  
   下載這個由LEOYoon-Tsaw所編譯的版本，下載完安裝pkg檔後會系統登出，再次登入如果還是沒看到，就再安裝一次，我自己是這樣解決的。
2. 打開 鍵盤偏好/輸入方式，按+ 選擇簡體中文，裡面會有鼠鬚管，不過我個人是在使用1.的方法解決後，才在去簡體中文中找到的，所以不能確定這個是不是正確的方式，不介意的話，可以先去簡體中文中查看有無鼠鬚管選項。
<img width="780" alt="截圖 2021-10-29 下午10 07 41" src="https://user-images.githubusercontent.com/32410486/139449518-f320d1a9-e7bd-435e-ad36-d9c57301ed81.png">

**Comment by Ponpon55837** [comment]
這邊要說明一下，由於LEOYoon-Tsaw所編譯的版本是他個人所使用的輸入法，有可能跟你自己使用的輸入法是不相同的，如果怕要重新設定一次很麻煩的話，就在/Users/你的本機名稱/Library/Rime，這個路徑底下先去備份你的資料出來，安裝完畢確認鼠鬚管可以使用後，直接回到這個資料夾把裡面文件都刪掉，放入原本備份的文件即可

**Comment by opo2000tw** [comment]
用 brew install --cask squirrel 安裝

之後複製貼上就可以了

**Comment by Ponpon55837** [comment]
> 用 brew install --cask squirrel 安裝
> 
> 之後複製貼上就可以了

https://github.com/rime/squirrel/issues/590#issuecomment-951941757

感謝你的回覆，不過包括我在內，有蠻多人在 Monterey 這個版本無法安裝使用的，詳細可以看我貼的這篇issue。

**Comment by opo2000tw** [comment]
> > 用 brew install --cask squirrel 安裝
> > 之後複製貼上就可以了
> 
> [rime/squirrel#590 (comment)](https://github.com/rime/squirrel/issues/590#issuecomment-951941757)
> 
> 感謝你的回覆，不過包括我在內，有蠻多人在 Monterey 這個版本無法安裝使用的，詳細可以看我貼的這篇issue。

系統版本： 12.0.1
硬體：MacBook Pro 15 2015
使用homebrew安裝鼠鬚管0.15.2

不好意思誤以爲可以，我用以下做法

1. brew
2. 安裝後出現三個圖示有移除後新增

```
==> Downloading https://github.com/rime/squirrel/releases/download/0.15.2/Squirrel-0.15.2.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/3777210/2db55b80-accf-11eb-89cd-cd5b71f719b7?X-Amz-A
######################################################################## 100.0%
```

**Comment by Ponpon55837** [comment]
最新版本0.16.2已無此問題
