### ISSUE TITLE
請問有辦設定韻母或韻腳自動修改嗎？

### ISSUE THREAD

**Issue by z20240** [Ponpon55837/Squirrel#4]
在 windows 或是 Marcos 內建的注音輸入法中若是韻母或韻腳打錯，我們僅需要直接輸入正確的韻母或韻腳即可校正。

但是在鼠鬚管中，我們要自己刪掉錯誤的韻母或韻腳才能再繼續輸入正確的韻母或韻腳。

若是直接輸入想要校正部分，鼠鬚管通常就會直接視為英文or其他 char 
Ex. 當我想打 ㄎㄢ 不小心打成 ㄎㄞ ，我不能直接打 ㄎㄞㄢ 讓輸入法自動校正成 ㄎㄢ （鼠鬚管會將這解讀成d80 之類的），而是必須自己手動刪除 ㄞ 再另外輸入 ㄢ才能達到目的。

不確定這是否能夠透過設定來達成這個效果？

**Comment by Ponpon55837** [comment]
> Ex. 當我想打 ㄎㄢ 不小心打成 ㄎㄞ ，我不能直接打 ㄎㄞㄢ 讓輸入法自動校正成 ㄎㄢ （鼠鬚管會將這解讀成d80 之類的），而是必須自己手動刪除 ㄞ 再另外輸入 ㄢ才能達到目的。
> 
> 不確定這是否能夠透過設定來達成這個效果？
> 

在鼠鬚管中輸入方式確實如同你所述，**無法直接輸入其它韻腳**進行代替。

但是洋蔥輸入法這個輸入碼表是支援不用完整輸入的方式。
ex
<img width="267" alt="截圖 2021-11-07 上午8 53 15" src="https://user-images.githubusercontent.com/32410486/140628273-80eded1f-4562-4fde-935d-011a78f15406.png">

如果你本身已經累積足夠的字庫，輸入方式就能簡化很多。
當然，這個回答可能不符合你的需求，如果有想修改輸入方式去符合自己的需求，可能還是要去鼠鬚管的github研究，並自行修改輸入碼表。

**Comment by z20240** [comment]
了解了，非常感謝您。
