### ISSUE TITLE
是否能更改選字按 CTRL？

### ISSUE THREAD

**Issue by Cookie755233** [Ponpon55837/Squirrel#7]
現在選字必須按著control才能選字，有沒有辦法更改這個設定？
mac的ctrl在左下角不太方便希望有辦法自定義

**Comment by Ponpon55837** [comment]
可以用鍵盤的上下左右方向鍵選字喔

要更改設定可以在default.cutsom.yaml最下面註解的
`#  ascii_composer/switch_key:`
在這邊去對你要用的快速鍵加上commit_code這個選字上屏的功能

當然因為每個人使用情況大不相同，可以研究一下鼠鬚管的定製指南手動看看喔
https://github.com/rime/home/wiki/CustomizationGuide
