### ISSUE TITLE
台灣詞庫繁中漢語拼音能否使用？

### ISSUE THREAD

**Issue by richblack** [Ponpon55837/Squirrel#8]
我剛剛安裝了鼠鬚管，目前使用中國詞庫，有點麻煩的是台灣常用語不會出現，所以我常常要選字訓練它。看到您的這份似乎是有台灣常用語詞庫，很想使用，但我是習慣用繁中漢語拼音的，就是明月拼音的輸入法，看到您的詞庫裡是有拼音加聲調，不過明月拼音是不用打聲調的。

想請問如果我用明月拼音可以用您的這份嗎？還是要重新整理過？謝謝！

**Comment by Ponpon55837** [comment]
這份純注音碼表是由洋蔥純注音修改而來的，洋蔥有建立拼音碼表https://github.com/oniondelta/Onion_Rime_Files，你可以參考看看或許對你會有幫助
